import { Header } from "@/components/other-header"
import { Footer } from "@/components/footer"

const text = "text-gray-600 leading-relaxed text-sm sm:text-base"
const title = "text-xl sm:text-2xl font-bold text-[#C8A96B] mb-3 sm:mb-4 text-balance"
const subtitle = "text-base sm:text-lg font-semibold text-gray-700 mb-2 sm:mb-3"
const list = "list-disc list-inside space-y-1 sm:space-y-2 text-gray-600 ml-2 sm:ml-4 text-sm sm:text-base"

function P({ children }: { children: React.ReactNode }) { return <p className={text}>{children}</p> }
function List({ children }: { children: React.ReactNode }) { return <ul className={list}>{children}</ul> }
function Sub({ name, children }: { name: string; children: React.ReactNode }) {
  return <div><h3 className={subtitle}>{name}</h3><div className="space-y-2">{children}</div></div>
}

function SoftwareConditions() {
  return <>
    <section><h2 className={title}>DISPOSITIONS PRÉLIMINAIRES</h2><div className="space-y-3 sm:space-y-4">
      <P>Les présentes conditions générales de vente (ci-après les « CGV ») régissent, de manière exclusive et impérative, l&apos;ensemble de la relation contractuelle entre LAHALEX (ci-après « l&apos;Éditeur ») et ses clients (ci-après le « Client »), s&apos;agissant de l&apos;acquisition, par achat ou par abonnement, de la licence d&apos;utilisation et de la maintenance des logiciels LAHALEX Avocat, LAHALEX Notaire et LAHALEX Commissaire de Justice (ci-après désignés individuellement ou collectivement les « Logiciels »).</P>
      <P>Ces CGV s&apos;appliquent pleinement au Client, priment sur toute condition d&apos;achat ou stipulation contraire, et ne peuvent être amendées que par un accord écrit signé par LAHALEX. L&apos;Éditeur conserve la faculté, à sa seule discrétion, de faire évoluer à tout moment les présentes CGV ainsi que ses tarifs, sans préavis ni obligation de justification.</P>
      <P>Toute commande passée par le Client, qu&apos;elle porte sur un Achat ou un Abonnement, emporte acceptation irrévocable et sans réserve des présentes CGV.</P>
    </div></section>
    <Article name="ARTICLE 1 — OBJET ET PORTÉE DES LOGICIELS">
      <Sub name="1.1 Description des Logiciels"><P>Les Logiciels constituent des solutions informatiques professionnelles spécialisées :</P><List><li>LAHALEX Avocat : logiciel de gestion de cabinet d&apos;avocat et d&apos;aide à la rédaction juridique ;</li><li>LAHALEX Notaire : logiciel de gestion d&apos;étude notariale et d&apos;aide à la rédaction d&apos;actes ;</li><li>LAHALEX Commissaire de Justice : logiciel de gestion d&apos;office et d&apos;aide aux procédures.</li></List></Sub>
      <Sub name="1.2 Modalités d&apos;acquisition : Achat ou Abonnement"><P>Le Client accède aux Logiciels selon l&apos;une des deux formules suivantes : l&apos;Achat de licence, moyennant le paiement d&apos;un prix unique et ouvrant droit à un usage pérenne, ou l&apos;Abonnement, moyennant une redevance périodique et ouvrant droit à un usage limité à la durée de l&apos;abonnement actif. L&apos;Achat inclut une période de maintenance gratuite de douze (12) mois. Aucun transfert de propriété n&apos;intervient dans le cadre de l&apos;Abonnement.</P></Sub>
      <Sub name="1.3 Prérequis techniques"><P>Le Client s&apos;engage à respecter les spécifications techniques minimales communiquées par LAHALEX et assume l&apos;entière responsabilité de la compatibilité de son environnement informatique au moment de l&apos;installation initiale.</P></Sub>
    </Article>
    <Article name="ARTICLE 2 — CONDITIONS FINANCIÈRES ET MODALITÉS DE RÈGLEMENT">
      <Sub name="2.1 Structure tarifaire"><P>En cas d&apos;Achat, les tarifs comprennent la licence d&apos;utilisation, la maintenance et le support initial pendant douze (12) mois, ainsi que, le cas échéant, les formations, accompagnements et modules additionnels optionnels et payants. En cas d&apos;Abonnement, la redevance périodique inclut le droit d&apos;usage, la maintenance et les mises à jour pendant toute la durée active, hors formations et modules optionnels.</P></Sub>
      <Sub name="2.2 Modalités de paiement"><List><li>Les prix sont établis en francs CFA (XOF), toutes taxes comprises.</li><li>Pour l&apos;Achat, le règlement s&apos;effectue comptant à la commande.</li><li>Pour l&apos;Abonnement, la facturation s&apos;effectue par avance au début de chaque période et se renouvelle automatiquement.</li><li>Les moyens acceptés sont le virement bancaire, la carte bancaire et le mobile money.</li><li>Tout paiement échelonné pour un Achat requiert l&apos;accord écrit préalable de LAHALEX.</li></List></Sub>
      <Sub name="2.3 Sanctions en cas de défaillance de paiement"><P>Tout retard entraîne une pénalité de 15 % du montant impayé, la suspension immédiate de la licence et des services, l&apos;exigibilité de l&apos;intégralité des sommes dues et une indemnité forfaitaire de recouvrement d&apos;un minimum de soixante-cinq mille (65 000) francs CFA. Pour l&apos;Achat, LAHALEX peut résilier de plein droit en conservant les sommes versées et la période de maintenance restante. Pour l&apos;Abonnement, l&apos;abonnement est résilié sans remboursement.</P></Sub>
    </Article>
    <Article name="ARTICLE 3 — RÉSERVE DE PROPRIÉTÉ ET TRANSFERT DE RISQUES"><P>Les dispositions du présent article s&apos;appliquent exclusivement à l&apos;Achat de licence. Dans le cadre d&apos;un Abonnement, le Client ne devient jamais propriétaire du Logiciel et son droit d&apos;usage cesse à l&apos;expiration ou à la résiliation.</P><Sub name="3.1 Principe de réserve de propriété"><P>LAHALEX demeure propriétaire exclusif des Logiciels acquis par Achat et de tous leurs composants jusqu&apos;au complet paiement du prix, même en cas de livraison, d&apos;installation, de commencement d&apos;utilisation ou de procédure collective.</P></Sub><Sub name="3.2 Conséquences de la réserve de propriété"><P>En cas d&apos;impayé, LAHALEX peut revendiquer la propriété des Logiciels, procéder à leur désinstallation, récupérer les supports et documentations et exiger la restitution des éléments fournis.</P></Sub><Sub name="3.3 Transfert des risques"><P>Les risques sont transférés au Client dès la livraison ou la mise à disposition. Le Client assume les risques de perte, de détérioration, de dysfonctionnement et les conséquences de toute utilisation inappropriée.</P></Sub></Article>
    <Article name="ARTICLE 4 — LICENCES D&apos;UTILISATION ET PROPRIÉTÉ INTELLECTUELLE"><Sub name="4.1 Propriété intellectuelle exclusive"><P>LAHALEX détient l&apos;intégralité des droits de propriété intellectuelle sur les Logiciels, leurs codes sources et exécutables, bases de données, marques, brevets, savoir-faire, documentations et supports.</P></Sub><Sub name="4.2 Licence d&apos;utilisation restrictive"><P>La licence est personnelle, non cessible, non exclusive, strictement limitée à un usage professionnel interne et révocable en cas de violation. Elle est pérenne pour un Achat, sous réserve du respect des CGV, et temporaire pour un Abonnement.</P></Sub><Sub name="4.3 Limitations et interdictions absolues"><P>Le Client s&apos;interdit de reproduire, copier, décompiler, désassembler, modifier, adapter, distribuer, louer, prêter, sous-licencier les Logiciels, créer des produits concurrents, supprimer les mentions de propriété intellectuelle ou accorder des accès à des tiers non autorisés.</P></Sub><Sub name="4.4 Utilisation multi-postes"><P>Le nombre d&apos;utilisateurs simultanés est limité ; chaque poste doit être déclaré et autorisé par LAHALEX. Toute utilisation excédentaire entraîne une facturation supplémentaire et un audit peut être exigé.</P></Sub><Sub name="4.5 Sanctions en cas de violation"><P>Toute violation entraîne la résiliation immédiate, sans remboursement, des dommages-intérêts forfaitaires d&apos;un minimum de trente-deux millions huit cent mille (32 800 000) francs CFA par violation, ainsi que l&apos;engagement de la responsabilité civile et pénale du Client.</P></Sub></Article>
    <Article name="ARTICLE 5 — LIVRAISON ET INSTALLATION"><Sub name="5.1 Modalités de livraison"><P>La livraison peut s&apos;effectuer par téléchargement sécurisé, support physique, installation sur site ou installation à distance, selon les modalités convenues.</P></Sub><Sub name="5.2 Délais de livraison"><P>Les délais sont indicatifs. LAHALEX ne peut être tenue responsable des retards dus à la force majeure, aux prestataires tiers, à l&apos;impossibilité d&apos;accès aux locaux ou à la non-conformité de l&apos;environnement du Client.</P></Sub><Sub name="5.3 Réception et recette"><P>Le Client dispose de quinze (15) jours ouvrables après la livraison pour signaler par écrit tout défaut de conformité. Passé ce délai, la livraison est réputée conforme et acceptée.</P></Sub></Article>
    <Article name="ARTICLE 6 — MAINTENANCE ET SUPPORT TECHNIQUE"><Sub name="6.1 Maintenance incluse selon la formule choisie"><P>Pour un Achat, la maintenance gratuite de douze (12) mois comprend les mises à jour correctives, le support de base, les adaptations réglementaires critiques et les optimisations mineures. Pour un Abonnement, la maintenance, les mises à jour et le support sont inclus pendant toute la durée active.</P></Sub><Sub name="6.2 Maintenance payante post-garantie (Achat)"><P>Après les douze (12) mois gratuits d&apos;un Achat, la maintenance payante comprend les mises à jour d&apos;évolution, le support avancé, les adaptations réglementaires, les optimisations majeures et les corrections non critiques.</P></Sub><Sub name="6.3 Niveaux de support technique"><P>Le support est proposé en niveaux Standard, Prioritaire ou Premium, applicables aux deux formules.</P></Sub><Sub name="6.4 Exclusions de maintenance"><P>Sont exclus les formations, les interventions liées à l&apos;environnement du Client, les conséquences d&apos;une utilisation non conforme, les personnalisations non autorisées et les dommages causés par des tiers ou la force majeure.</P></Sub><Sub name="6.5 Contrat de maintenance post-garantie (Achat)"><P>Après la période gratuite, la maintenance fait l&apos;objet d&apos;un contrat séparé d&apos;au moins douze (12) mois, facturé annuellement par avance, avec préavis de résiliation de trois (3) mois.</P></Sub></Article>
    <Article name="ARTICLE 7 — GARANTIES ET RESPONSABILITÉ"><Sub name="7.1 Garantie de conformité"><P>En cas d&apos;Achat, LAHALEX garantit pendant 90 jours la conformité du Logiciel aux spécifications, son fonctionnement normal et l&apos;absence de défaut majeur. LAHALEX peut corriger le défaut ou rembourser le montant payé.</P></Sub><Sub name="7.2 Limitation de responsabilité"><P>LAHALEX exclut les dommages indirects, pertes de données, d&apos;exploitation ou de bénéfices, préjudices commerciaux et conséquences d&apos;une utilisation inappropriée. Sa responsabilité est plafonnée au montant effectivement payé par le Client.</P></Sub><Sub name="7.3 Absence de garantie"><P>LAHALEX ne garantit pas l&apos;adaptation aux besoins spécifiques, le fonctionnement ininterrompu, la compatibilité évolutive ni les résultats particuliers.</P></Sub><Sub name="7.4 Usage frauduleux"><P>Aucune responsabilité de LAHALEX ne peut être engagée pour les conséquences d&apos;un usage frauduleux ou non autorisé des accès du Client.</P></Sub></Article>
    <Article name="ARTICLES 8 À 15 — DISPOSITIONS COMPLÉMENTAIRES"><Sub name="ARTICLE 8 — Formation et accompagnement"><P>LAHALEX propose des formations payantes et des accompagnements sur mesure : analyse des besoins, migration, intégration et assistance au changement.</P></Sub><Sub name="ARTICLE 9 — Évolution et mises à jour"><P>LAHALEX peut faire évoluer les fonctionnalités, modifier l&apos;interface, s&apos;adapter aux évolutions réglementaires et interrompre le support des versions obsolètes. Pour l&apos;Achat, les mises à jour sont gratuites la première année puis payantes ; pour l&apos;Abonnement, elles sont incluses pendant la durée active.</P></Sub><Sub name="ARTICLE 10 — Données et confidentialité"><P>Le Client conserve la propriété de ses données métier. LAHALEX les traite selon sa politique de confidentialité et met en place des mesures de sécurité appropriées. Le Client reste responsable de la sauvegarde et de la sécurisation de ses données.</P></Sub><Sub name="ARTICLE 11 — Résiliation"><P>Pour l&apos;Abonnement, le Client peut résilier à l&apos;échéance de chaque période avec un préavis de trois (3) mois. Pour l&apos;Achat, la licence ne peut être résiliée périodiquement. LAHALEX peut résilier en cas de défaut de paiement, violation, usage frauduleux, atteinte à la propriété intellectuelle ou procédure collective. La résiliation entraîne la cessation du droit d&apos;utilisation, la désactivation des licences et la destruction des copies.</P></Sub><Sub name="ARTICLES 12 À 15 — Dispositions finales"><P>Les licences sont personnelles et intransmissibles. Le Client respecte les sanctions internationales et les contrôles à l&apos;exportation. LAHALEX est exonérée en cas de cyberattaques, pannes de réseaux ou défaillances d&apos;infrastructures hors de son contrôle. Le contrat est régi par le droit béninois et relève des tribunaux de la République du Bénin, notamment du Tribunal de Commerce de Cotonou.</P></Sub></Article>
    <div className="bg-gray-50 p-4 sm:p-6 rounded-lg mt-8 border border-[#C8A96B]/20"><P><strong>ACCEPTATION OBLIGATOIRE</strong></P><P>Toute commande de Logiciels LAHALEX, qu&apos;elle porte sur un Achat ou un Abonnement, emporte acceptation pleine et entière des présentes Conditions Générales de Vente.</P><p className="text-xs sm:text-sm text-gray-500 mt-3">Version : 1.0 — LAHALEX se réserve le droit de modifier ces conditions à tout moment. La version applicable est celle en vigueur à la date de commande.</p></div>
  </>
}
function Article({ name, children }: { name: string; children: React.ReactNode }) {
  return <section><h2 className={title}>{name}</h2><div className="space-y-4 sm:space-y-6">{children}</div></section>
}

function UpdatedConditions() {
  return <>
    <section><h2 className={title}>DISPOSITIONS PRÉLIMINAIRES</h2><div className="space-y-3 sm:space-y-4">
      <P>Les présentes conditions générales de vente et d&apos;abonnement (ci-après les « CGVA ») encadrent, de façon exclusive et impérative, l&apos;ensemble de la relation contractuelle liant LAHALEX (ci-après « l&apos;Éditeur ») à ses clients (ci-après le « Client »), s&apos;agissant de l&apos;accès, de l&apos;utilisation et de l&apos;abonnement à ses produits et services.</P>
      <P>Ces CGVA s&apos;appliquent pleinement au Client et priment sur toute condition d&apos;achat ou stipulation contraire, sous réserve du texte directement signé avec le Client, qui prévaut en cas de contradiction avec les présentes CGVA. L&apos;Éditeur conserve la faculté, à sa seule discrétion, de faire évoluer à tout moment les présentes CGVA ainsi que ses tarifs, sans préavis ni obligation de justification. La version des CGVA opposable au Client est celle en vigueur à la date de sa souscription.</P>
      <P>Toute commande passée par le Client emporte acceptation des présentes CGVA.</P>
    </div></section>

    <Article name="ARTICLE 1 — CONDITIONS FINANCIÈRES ET RÈGLEMENT">
      <Sub name="1.1 Modalités de facturation"><P>Les tarifs sont exprimés en francs CFA (XOF), hors taxes. La facturation intervient par anticipation, au début de chaque période contractuelle, y compris pour les Bases de données LAHALEX Universel (voir Article 10.7). Le Client accepte expressément que la facturation électronique constitue l&apos;unique mode de transmission des factures.</P></Sub>
      <Sub name="1.2 Modalités de paiement"><P>Le règlement s&apos;effectue au comptant, sans escompte, selon les moyens de paiement acceptés par LAHALEX (virement, prélèvement, carte bancaire, mobile money). Tout paiement fractionné suppose l&apos;accord écrit préalable de LAHALEX ainsi que la mise en place obligatoire d&apos;un prélèvement automatique.</P><P>LAHALEX peut, à sa seule discrétion :</P><List><li>refuser, modifier ou résilier tout échéancier de paiement, sans préavis ;</li></List></Sub>
      <Sub name="1.3 Sanctions en cas de défaillance de paiement"><P>Tout retard de paiement entraîne :</P><List><li>la suspension de l&apos;accès aux services trente (30) jours après un rappel écrit resté sans effet ;</li><li>l&apos;exigibilité immédiate de la totalité des sommes dues au titre de la période contractuelle ;</li></List></Sub>
    </Article>

    <Article name="ARTICLE 2 — DURÉE ET RÉSILIATION DU CONTRAT">
      <Sub name="2.1 Durée d&apos;engagement"><P>Sauf stipulation contraire, l&apos;abonnement est souscrit pour une durée minimale d&apos;un mois, reconductible tacitement. Les abonnements annuels sont conclus pour une durée de douze (12) mois, reconduits tacitement sauf résiliation notifiée dans les conditions prévues à l&apos;article 2.2.</P></Sub>
      <Sub name="2.2 Résiliation à l&apos;initiative du Client"><P>Le Client ne peut résilier son abonnement mensuel depuis son espace personnel en ligne ou avec le service client par voie électronique. La résiliation prend effet à l&apos;issue de la période mensuelle en cours, sans remboursement des sommes déjà versées.</P></Sub>
      <Sub name="2.3 Résiliation à l&apos;initiative de LAHALEX"><P>LAHALEX peut résilier le contrat trente (30) jours après une mise en demeure notifiée par écrit et restée sans effet, notamment en cas de violation des présentes CGVA, d&apos;usage abusif ou frauduleux, de défaut de paiement, de comportement portant atteinte à l&apos;image ou aux intérêts de LAHALEX ou de non-respect des obligations de confidentialité.</P></Sub>
    </Article>

    <Article name="ARTICLE 3 — DROITS D&apos;UTILISATION ET PROPRIÉTÉ INTELLECTUELLE">
      <Sub name="3.1 Propriété des contenus"><P>LAHALEX détient ou a valablement acquis l&apos;ensemble des droits de propriété intellectuelle ou droit d&apos;utilisation afférents à ses produits, services, contenus et documentations. Aucun droit de propriété n&apos;est cédé ou transféré au Client à quelque titre que ce soit.</P></Sub>
      <Sub name="3.2 Licence d&apos;utilisation restrictive"><P>Le Client se voit consentir une licence d&apos;usage personnelle, non exclusive, incessible, strictement limitée à un usage documentaire interne.</P></Sub>
      <Sub name="3.3 Interdictions absolues"><P>Le Client s&apos;interdit formellement et s&apos;engage à ne pas :</P><List><li>reproduire, copier, diffuser ou redistribuer tout ou partie des contenus ;</li><li>procéder à l&apos;extraction substantielle ou à la réutilisation systématique des bases de données ;</li><li>concéder à un tiers un quelconque droit d&apos;accès ;</li><li>utiliser les contenus à des fins commerciales ou de revente ;</li><li>porter atteinte aux droits de LAHALEX ou de ses partenaires ;</li><li>procéder à l&apos;ingénierie inverse des logiciels ou services.</li></List></Sub>
      <Sub name="3.4 Sanctions en cas de violation"><P>Toute violation des droits de propriété intellectuelle entraîne :</P><List><li>la résiliation immédiate du contrat, sans remboursement ;</li><li>l&apos;engagement de la responsabilité civile et pénale du Client ;</li><li>le versement de dommages-intérêts forfaitaires d&apos;un montant de six millions cinq cent mille (6 500 000) francs CFA (XOF) par violation constatée ;</li><li>l&apos;obligation de cesser immédiatement toute utilisation illicite.</li></List></Sub>
    </Article>

    <Article name="ARTICLE 4 — RESPONSABILITÉ ET GARANTIES">
      <Sub name="4.1 Responsabilité du Client"><P>Le Client assume l&apos;entière responsabilité de l&apos;utilisation et de l&apos;interprétation des contenus et services, de la sélection et de l&apos;exploitation des informations consultées, des décisions prises sur cette base, de la sécurité de ses systèmes et données et du respect de la réglementation qui lui est applicable.</P></Sub>
      <Sub name="4.2 Limitation de responsabilité de LAHALEX"><P>La responsabilité de LAHALEX est expressément exclue s&apos;agissant de l&apos;exhaustivité, de l&apos;exactitude ou de la mise à jour des informations diffusées, des dommages indirects, accessoires ou immatériels, des pertes de données, d&apos;exploitation ou de chance et des conséquences résultant de l&apos;utilisation des services. Les interruptions temporaires n&apos;ouvrent droit à aucune indemnisation, sous réserve du mécanisme de prolongation gratuite prévu à l&apos;article 10.7. Dans l&apos;hypothèse où la responsabilité de LAHALEX serait retenue, l&apos;indemnisation sera plafonnée au montant de l&apos;abonnement en cours.</P></Sub>
      <Sub name="4.3 Absence de garantie"><P>LAHALEX ne garantit ni le fonctionnement ininterrompu des services, ni un résultat particulier lié à leur utilisation, ni l&apos;absence d&apos;anomalie ou de défaillance technique.</P></Sub>
    </Article>

    <Article name="ARTICLE 5 — CONFIDENTIALITÉ ET DONNÉES PERSONNELLES"><Sub name="5.1 Obligations du Client"><P>Le Client garantit la licéité et la conformité de toutes les données qu&apos;il transmet à LAHALEX, et en assume l&apos;entière responsabilité quant à leur contenu.</P></Sub><Sub name="5.2 Traitement par LAHALEX"><P>LAHALEX traite les données conformément à la réglementation béninoise applicable, notamment le Code du numérique en République du Bénin, ainsi qu&apos;à sa Charte relative aux données personnelles. Ces données sont conservées pour la durée nécessaire à l&apos;exécution du contrat et au respect des obligations légales de LAHALEX.</P></Sub></Article>
    <Article name="ARTICLE 6 — SANCTIONS INTERNATIONALES"><P>Le Client garantit que lui-même et ses utilisateurs ne font l&apos;objet d&apos;aucune sanction internationale, n&apos;accéderont pas aux services depuis un territoire soumis à embargo, ne donneront accès aux services à aucune partie sanctionnée et respecteront les réglementations relatives aux contrôles à l&apos;exportation. Toute violation entraîne la résiliation immédiate du contrat et engage la responsabilité du Client.</P></Article>
    <Article name="ARTICLE 7 — ÉVOLUTION DES SERVICES"><P>LAHALEX se réserve le droit de modifier, suspendre ou interrompre ses services, de faire évoluer ses fonctionnalités, contenus ou supports, d&apos;adapter sa politique tarifaire et de modifier les présentes CGVA. Ces modifications s&apos;imposent au Client sans préavis ni indemnisation.</P></Article>
    <Article name="ARTICLE 8 — DISPOSITIONS GÉNÉRALES"><P>Le présent contrat est exclusivement régi par le droit de la République du Bénin. En cas de litige, seuls les tribunaux de la République du Bénin sont compétents, en particulier le Tribunal de Commerce de Cotonou. Si une clause est déclarée nulle ou inapplicable, les autres dispositions conservent leur validité. Les conditions particulières signées avec le Client priment sur les présentes CGVA en cas de contradiction.</P></Article>

    <Article name="ARTICLE 9 — CONDITIONS PARTICULIÈRES : SERVICES EN LIGNE">
      <Sub name="9.1 Conditions d&apos;accès aux services"><Sub name="9.1.1 Prérequis techniques et responsabilités du Client"><P>Le Client assume les coûts de sa connexion Internet, la compatibilité de son équipement, le respect des spécifications minimales et la mise en œuvre de mesures de sécurité et de sauvegarde appropriées. Sa configuration doit être exempte de virus, fonctionnelle, compatible et protégée contre les intrusions.</P></Sub><Sub name="9.1.2 Disponibilité des services"><P>Les services sont en principe accessibles 24h/24 et 7j/7, sous réserve des interruptions de maintenance, d&apos;évolution technique, d&apos;incidents indépendants de LAHALEX ou de mesures de sécurité.</P></Sub><Sub name="9.1.3 Support technique"><P>Un service d&apos;assistance limité à l&apos;usage des services est mis à disposition selon les horaires fixés par LAHALEX.</P></Sub><Sub name="9.1.4 Interdictions absolues"><P>Le Client s&apos;interdit tout accès frauduleux, toute perturbation, introduction de virus, intrusion, piratage, usage contraire à la destination des services ou atteinte à la sécurité de la plateforme.</P></Sub></Sub>
      <Sub name="9.2 Modalités d&apos;abonnement et de facturation"><Sub name="9.2.1 Principe de facturation structurelle"><P>Les abonnements sont souscrits sur la base du nombre total d&apos;utilisateurs composant la structure du Client, sans exception.</P></Sub><Sub name="9.2.2 Obligations déclaratives du Client"><P>Le Client doit déclarer toute modification de sa situation professionnelle et toute variation du nombre d&apos;utilisateurs, accepter les ajustements rétroactifs déterminés par LAHALEX et régulariser sa situation au renouvellement.</P></Sub><Sub name="9.2.3 Contrôles et vérifications par LAHALEX"><P>LAHALEX peut solliciter une attestation, imposer un délai maximal de 30 jours pour les justificatifs et procéder à des vérifications ponctuelles ou systématiques.</P></Sub></Sub>
      <Sub name="9.3 Gestion des accès et authentification"><Sub name="9.3.1 Attribution des identifiants"><P>LAHALEX attribue des codes personnalisés, un accès IP exceptionnel ou une délégation d&apos;authentification. Les modalités peuvent être modifiées à tout moment.</P></Sub><Sub name="9.3.2 Caractère strictement personnel des accès"><P>Les identifiants sont personnels, intransmissibles, confidentiels et réservés aux utilisateurs autorisés. Le Client répond de leur confidentialité.</P></Sub><Sub name="9.3.3 Obligations de sécurité"><P>Le Client assume la préservation de ses identifiants, la sécurisation de ses terminaux et réseaux, l&apos;exactitude de ses informations et le signalement de tout usage suspect.</P></Sub><Sub name="9.3.4 Responsabilité en cas d&apos;usage non autorisé"><P>Le Client demeure responsable de tout usage effectué avec ses identifiants et de ses conséquences financières et juridiques.</P></Sub></Sub>
    </Article>

    <Article name="ARTICLE 10 — DISPOSITIONS COMPLÉMENTAIRES APPLICABLES AUX BASES DE DONNÉES LAHALEX UNIVERSEL">
      <Sub name="10.1 Caractère exceptionnel des réductions accordées"><P>Les réductions accordées par LAHALEX sont exceptionnelles, dérogatoires et conditionnées au maintien des éléments ayant justifié leur octroi. Elles ne créent aucun droit acquis ni obligation de maintenir les mêmes conditions tarifaires.</P></Sub>
      <Sub name="10.2 Résiliation complémentaire"><P>Le non-respect des échéances entraîne, après notification, la suspension des plateformes puis, après trente (30) jours sans régularisation, la résiliation. Le CLIENT coopère à la récupération, l&apos;exportation ou la suppression des données dans des conditions sécurisées.</P></Sub>
      <Sub name="10.3 Propriété intellectuelle de la Plateforme LAHALEX Universel"><P>La Plateforme, son code source, son design, ses contenus et bases de données demeurent la propriété exclusive de LAHALEX. Le CLIENT bénéficie d&apos;une licence non exclusive, non cessible et non transférable, limitée à la durée de l&apos;abonnement et aux Utilisateurs Autorisés.</P></Sub>
      <Sub name="10.4 Interdictions relatives aux ressources documentaires"><P>Sauf autorisation expresse, le CLIENT et les Utilisateurs s&apos;interdisent de modifier, copier, extraire, diffuser ou mettre à disposition les ressources documentaires, d&apos;utiliser les marques et logos ou de faire un usage abusif des autorisations consenties.</P></Sub>
      <Sub name="10.5 Suspension d&apos;accès aux Bases de données LAHALEX Universel"><P>Après un rappel et un délai de trente (30) jours, LAHALEX peut suspendre l&apos;accès aux Bases de données depuis l&apos;adresse IP du CLIENT, sans réduction du prix ni suppression des sommes dues.</P></Sub>
      <Sub name="10.6 Obligations du Client relatives à l&apos;accès aux Bases de données"><P>L&apos;accès aux ressources est réservé aux seuls Utilisateurs autorisés. En cas d&apos;accès à distance, une authentification individuelle et personnelle est requise. Le CLIENT informe immédiatement LAHALEX de toute utilisation non autorisée.</P></Sub>
      <Sub name="10.7 Conditions financières spécifiques aux Bases de données LAHALEX Universel"><P>Le prix de la licence est fixé par LAHALEX. Le premier abonnement peut être payé avec un acompte de 50 %, le solde étant dû avant l&apos;activation complète. En cas de renouvellement, la facturation est anticipée. Si les interruptions cumulées dépassent sept (7) jours sur une année, la licence est prolongée gratuitement d&apos;une durée équivalente. La responsabilité de LAHALEX est limitée au montant de la licence payé.</P></Sub>
      <Sub name="10.8 Obligations de LAHALEX relatives à la Plateforme LAHALEX Universel"><P>LAHALEX donne accès pendant la durée de la licence aux ressources documentaires, scientifiques et pédagogiques disponibles ainsi qu&apos;aux nouvelles ressources validées. Elle met tout en œuvre pour assurer la disponibilité du service et informe le CLIENT des modifications significatives. Les ressources restent soumises aux droits de diffusion et aux limitations du présent contrat. Le CLIENT bénéficie également d&apos;un accès « pérenne » selon les modalités définies par LAHALEX.</P></Sub>
    </Article>
  </>
}

export default function ConditionsGeneralesPage() {
  return <div className="flex flex-col min-h-screen bg-white font-sf-pro"><Header /><main className="flex-1"><section className="bg-white py-8 sm:py-12 md:py-16 lg:py-20"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="text-center mb-6 sm:mb-8 lg:mb-12"><h1 className="font-gobold text-2xl sm:text-3xl md:text-4xl lg:text-5xl text-gray-700 mb-4 sm:mb-6 leading-tight text-balance">CONDITIONS GÉNÉRALES DE VENTE ET D&apos;ABONNEMENT - LAHALEX</h1></div><div className="max-w-5xl mx-auto"><div className="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden"><div className="p-4 sm:p-6 md:p-8 space-y-6 sm:space-y-8"><UpdatedConditions /><div className="border-t-2 border-[#C8A96B] pt-8 mt-8"><div className="text-center mb-6 sm:mb-8"><h1 className="font-gobold text-xl sm:text-2xl md:text-3xl lg:text-4xl text-gray-700 mb-4 sm:mb-6 leading-tight text-balance">CONDITIONS GÉNÉRALES DE VENTE — LOGICIELS LAHALEX</h1><p className="text-xs sm:text-sm text-gray-500">Version : Septembre 2026</p><p className="text-xs sm:text-sm text-gray-500">Document contractuel opposable</p></div><SoftwareConditions /></div></div></div></div></div></section></main><Footer /></div>
}
